# Importamos librerías

In [1]:
import numpy as np

# Escalares

In [2]:
x = np.array(42)

In [3]:
print(x.shape)

()


In [4]:
x.ndim

0

# Vectores

In [5]:
x = np.array([42,5, 8,2,9,8,7])

In [6]:
print(x.shape)

(7,)


In [7]:
x.ndim

1

# Matrices

In [8]:
x = np.array([[42,5, 8,2,9,8,7],
             [5, 3, 67, 8, 9, 7, 1]])

In [9]:
print(x.shape)

(2, 7)


In [10]:
x.ndim

2

In [ ]:
# Tesnsores

In [15]:
x = np.array([[[42,5, 8,2,9,8,7],
             [5, 3, 67, 8, 9, 7, 1]],
             [[4,25, 1,2,9,5,7],
             [54, 3, 67, 7, 9, 7, 6]],
             [[42,5, 8,2,9,8,7],
             [5, 3, 67, 8, 9, 7, 1]]])

In [16]:
print(x.shape)

(3, 2, 7)


In [17]:
x.ndim

3

# Reshape

In [18]:
x = np.array([[0, 1],
              [2, 3],
              [4, 5],
              [6, 7],
              [8, 9],
              [10, 11]])  

In [19]:
x.shape

(6, 2)

In [21]:
x.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [23]:
x.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# Transpuesta

In [25]:
np.transpose(x)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [26]:
x.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])